### PR TITLE
fix: get network gateway SSID and signal strength using Windows APIs

### LINKED ISSUE #96: [Bug] netsh's output is localized and causes missing SSID & signal strength on non-English systems
### Describe the bug

Exactly what the title says. Zebar uses a simple regex over a netsh output to obtain signal information, but netsh output is localized for the language that the system is set to, and has no option to de-localize it.

Use a windows API instead.

### Reproduction

Set your system to any language other than English, like Spanish.

### Stack trace or error logs (if applicable)

_No response_

### Version number

i don't know, zebar --version doesn't work

### PR DESCRIPTION
**Pull request by SebasF1349**
Zebar was using `netsh` to get wifi data and then parse it using regex. That lead to some issues (#96) as `netsh` translates the data to the os language.

I have rewritten the whole `wifi_hotspot.rs` file to use the Windows API instead. This should be less error prone, but I had to use some unsafe functions and pointers that needed to be freed. After handling those I don't see any memory leaks in my tests, but it may be worth testing that again. Also, it should work with any Windows version that Tauri works on, but I can only test in Windows 10.

Let me know of any question or suggestion.

Closes #96 

Side note: I have removed the `Win32_System_Threading` feature as it doesn't seem to be used anywhere else.

### CODE REVIEW

File: packages/desktop/src/providers/network/wifi_hotspot.rs [hunk 1]
```diff
@@ -1,23 +1,34 @@
...
-/// Runs the netsh command and parses the output to get the primary
-/// interface's SSID and signal strength.
-//
-/// Unclear if the primary interface is always the default interface
-/// returned by the netdev/defaultnet crate - requires more testing.
+#[derive(Debug)]
+struct WlanHandle(HANDLE);
+
+impl Drop for WlanHandle {
+  fn drop(&mut self) {
```
Comment (lars-berger) [inline packages/desktop/src/providers/network/wifi_hotspot.rs:24]: Need to wrap in conditional for `windows` compilation

File: packages/desktop/src/providers/network/wifi_hotspot.rs [hunk 2]
```diff
@@ -1,23 +1,34 @@
...
+    unsafe {
+      WlanCloseHandle(self.0, None);
+    }
+  }
+}
+
+/// Gets wifi ssid and signal stregth using winapi
```
Comment (lars-berger) [inline packages/desktop/src/providers/network/wifi_hotspot.rs:31]: strength typo

File: packages/desktop/src/providers/network/wifi_hotspot.rs [hunk 3]
```diff
@@ -28,42 +39,72 @@ pub fn default_gateway_wifi() -> anyhow::Result<WifiHotstop> {
...
-      .and_then(|s| s.as_str().parse().ok());
+    // needed to remove leading zeros in array
+    let ssid_arr = atributes.dot11Ssid.ucSSID;
+    let mut ssid_vec = ssid_arr
+      .into_iter()
+      .rev()
+      .skip_while(|&byte| byte == 0)
+      .collect::<Vec<_>>();
+    ssid_vec.reverse();
+    let ssid = String::from_utf8(ssid_vec).unwrap();
```
Comment (lars-berger) [inline packages/desktop/src/providers/network/wifi_hotspot.rs:103]: Could we use `.context` here instead of `.unwrap`?

**Review by lars-berger — CHANGES_REQUESTED** [review]

**Comment by SebasF1349** [comment]
Fixed requested changes.

**Comment by lars-berger** [comment]
Perfect!! Thanks a bunch 🙌
